// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUyo5gDuo6RehLBoyRdEbq3hgTX5FQiCo',
    appId: '1:836532979243:web:a587977a68198a20a4cc6e',
    messagingSenderId: '836532979243',
    projectId: 'inclass-3e3a4',
    authDomain: 'inclass-3e3a4.firebaseapp.com',
    storageBucket: 'inclass-3e3a4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvAQ5SMcBNuwFvS0wid-v88lRsZYxnXXg',
    appId: '1:836532979243:android:b70cbcab3f81594aa4cc6e',
    messagingSenderId: '836532979243',
    projectId: 'inclass-3e3a4',
    storageBucket: 'inclass-3e3a4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBW5bcsTyjRRpbQFdVLliK0GcsNyhydDuY',
    appId: '1:836532979243:ios:fa2b9966698c115ba4cc6e',
    messagingSenderId: '836532979243',
    projectId: 'inclass-3e3a4',
    storageBucket: 'inclass-3e3a4.firebasestorage.app',
    iosBundleId: 'com.example.inclass13',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBW5bcsTyjRRpbQFdVLliK0GcsNyhydDuY',
    appId: '1:836532979243:ios:fa2b9966698c115ba4cc6e',
    messagingSenderId: '836532979243',
    projectId: 'inclass-3e3a4',
    storageBucket: 'inclass-3e3a4.firebasestorage.app',
    iosBundleId: 'com.example.inclass13',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUyo5gDuo6RehLBoyRdEbq3hgTX5FQiCo',
    appId: '1:836532979243:web:f4e01945eff3899aa4cc6e',
    messagingSenderId: '836532979243',
    projectId: 'inclass-3e3a4',
    authDomain: 'inclass-3e3a4.firebaseapp.com',
    storageBucket: 'inclass-3e3a4.firebasestorage.app',
  );
}
